name = "PlantShapes"
uuid = "f24173b7-d41b-4095-8363-c8e69e35ad9f"
authors = ["anaIFernst <ana.ferreiraernst@wur.nl> and contributors"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.6.7"